# Generated by Django 5.1.5 on 2025-02-02 22:14

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dr', 'Doctor'), ('MD', 'Doctor of Medicine'), ('DO', 'Doctor of Osteopathic Medicine')], max_length=4)),
                ('docFname', models.CharField(max_length=30)),
                ('docLname', models.CharField(max_length=30)),
                ('doc_type', models.CharField(max_length=30)),
                ('degrees', models.CharField(max_length=30)),
                ('specification', models.CharField(max_length=80)),
                ('state', models.CharField(choices="(('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'))", max_length=40)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('status', models.IntegerField(choices=[(0, 'Not Available'), (1, 'Available')], default=0)),
                ('min_price', models.IntegerField(blank=True, default=0, null=True)),
                ('high_price', models.IntegerField(blank=True, default=1000, null=True)),
                ('profile_image', models.ImageField(upload_to='')),
                ('price_per_hour', models.IntegerField()),
                ('feature_image', models.ImageField(upload_to='')),
                ('feature_image2', models.ImageField(upload_to='')),
                ('feature_image3', models.ImageField(upload_to='')),
                ('feature_image4', models.ImageField(upload_to='')),
                ('specialization', models.TextField(help_text='Enter your specialized duties')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
